# Generated by Django 5.2.6 on 2025-09-24 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#007bff', help_text='Couleur hex', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InfluencerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('PENDING', 'En attente'), ('VERIFIED', 'Vérifié'), ('REJECTED', 'Rejeté')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#28a745', max_length=7)),
            ],
            options={
                'verbose_name': 'Statut influenceur',
                'verbose_name_plural': 'Statuts influenceurs',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('YOUTUBE', 'YouTube'), ('TWITTER', 'Twitter'), ('FACEBOOK', 'Facebook'), ('LINKEDIN', 'LinkedIn')], max_length=20, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Classe CSS pour l'icône", max_length=50)),
            ],
            options={
                'verbose_name': 'Plateforme',
                'verbose_name_plural': 'Plateformes',
            },
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('profile_image', models.ImageField(blank=True, upload_to='influencers/profiles/')),
                ('niche_keywords', models.TextField(blank=True, help_text='Mots-clés séparés par des virgules')),
                ('engagement_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Localisation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='influencer.category', verbose_name='Catégorie')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='influencer.influencerstatus')),
            ],
            options={
                'verbose_name': 'Influenceur',
                'verbose_name_plural': 'Influenceurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name="Nom d'utilisateur")),
                ('followers_count', models.PositiveIntegerField(verbose_name="Nombre d'abonnés")),
                ('following_count', models.PositiveIntegerField(verbose_name="Nombre d'abonnements")),
                ('posts_count', models.PositiveIntegerField(verbose_name='Nombre de publications')),
                ('engagement_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Compte vérifié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='influencer.influencer')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='influencer.platform', verbose_name='Plateforme')),
            ],
            options={
                'verbose_name': 'Compte réseau social',
                'verbose_name_plural': 'Comptes réseaux sociaux',
                'unique_together': {('influencer', 'platform')},
            },
        ),
    ]
