# Generated by Django 5.2.6 on 2025-09-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='following_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
