# Generated by Django 5.2.6 on 2025-09-24 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("influencer", "0002_alter_socialmediaaccount_following_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="influencer",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="influencers",
                to="influencer.category",
                verbose_name="Catégorie",
            ),
        ),
    ]
