# Generated by Django 5.2.6 on 2025-09-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("influencer", "0003_alter_influencer_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediaaccount",
            name="posts_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Nombre de publications"
            ),
        ),
    ]
